Repository pusher/faros, pull requests merged in 2019-10, with the labels that each got.

#179 implement not reconciling gittrackobjects
  cmd/manager/main.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrackobject/gittrackobject_controller.go
  pkg/controller/gittrackobject/gittrackobject_controller_test.go
  pkg/controller/gittrackobject/handler_test.go
  pkg/controller/gittrackobject/metrics_test.go
  pkg/controller/gittrackobject/status_test.go
  pkg/controller/gittrackobject/watch_test.go
  pkg/flags/flagset.go
  pkg/utils/predicate.go
Labels: size/XXL

#181 Correct typo
  CONTRIBUTING.md
Labels: ok-to-test, size/XS

#183 Disallow GTMEnabled with namespace and CGTM set to any kind of enabled
  pkg/flags/flagset.go
Labels: size/XS
