Repository pusher/faros, pull requests merged in 2019-03, with the labels that each got.

#103 Add JUnit reporting capability to test suites
  pkg/apis/faros/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/gittrack/gittrack_controller_suite_test.go
  pkg/controller/gittrackobject/gittrackobject_controller_suite_test.go
  pkg/controller/gittrackobject/utils/utils_suite_test.go
  pkg/flags/flagset_test.go
  pkg/utils/decoder_test.go
  test/reporters/reporters.go
Labels: size/M

#104 Fix JUnit reporting configuration
  pkg/utils/client/client_suite_test.go
  test/reporters/reporters.go
Labels: size/XS

#105 Printer columns for gittracks, gittrackobjects, clustergittrackobjects
  Gopkg.lock
  config/crds/faros_v1alpha1_clustergittrackobject.yaml
  config/crds/faros_v1alpha1_gittrack.yaml
  config/crds/faros_v1alpha1_gittrackobject.yaml
  pkg/apis/faros/v1alpha1/clustergittrackobject_types.go
  pkg/apis/faros/v1alpha1/gittrack_types.go
  pkg/apis/faros/v1alpha1/gittrackobject_types.go
Labels: size/M

#97 Check for dry run support before sending updates
  pkg/controller/gittrackobject/handler.go
Labels: size/S

#107 Use unstructured codec in applier
  pkg/utils/client/apply.go
Labels: size/S

#94 Better build
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Makefile
  Makefile.tools
  README.md
  cmd/manager/main.go
  cmd/manager/version.go
  configure
  wercker.yml
Labels: size/XL

#109 Fix flaking tests
  pkg/controller/gittrackobject/gittrackobject_controller_suite_test.go
  pkg/controller/gittrackobject/gittrackobject_controller_test.go
  pkg/controller/gittrackobject/handler_test.go
  pkg/controller/gittrackobject/status_test.go
  pkg/controller/gittrackobject/watch_test.go
  test/utils/delete.go
Labels: lgtm, size/L

#96 Fix leader election flag in Readme
  README.md
Labels: ok-to-test, size/XS

#108 Add logging back to GTO controller
  pkg/controller/gittrackobject/gittrackobject_controller.go
  pkg/controller/gittrackobject/handler.go
Labels: size/S

#86 Add support for HTTP Basic Auth for private git repos
  README.md
  config/crds/faros_v1alpha1_gittrack.yaml
  pkg/apis/faros/v1alpha1/gittrack_types.go
  pkg/controller/gittrack/git_creds.go
  pkg/controller/gittrack/git_creds_test.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/utils/predicate.go
Labels: ok-to-test, size/L

#106 Hide some CRD columns under `-o wide` flag
  config/crds/faros_v1alpha1_clustergittrackobject.yaml
  config/crds/faros_v1alpha1_gittrack.yaml
  config/crds/faros_v1alpha1_gittrackobject.yaml
  pkg/apis/faros/v1alpha1/clustergittrackobject_types.go
  pkg/apis/faros/v1alpha1/gittrack_types.go
  pkg/apis/faros/v1alpha1/gittrackobject_types.go
Labels: size/S

#110 Fix gittrack controller comment
  pkg/controller/gittrack/gittrack_controller.go
Labels: size/XS
