Repository pusher/faros, pull requests merged in 2019-05, with the labels that each got.

#114 Improve debug logging
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_suite_test.go
  pkg/controller/gittrack/status.go
  pkg/controller/gittrackobject/gittrackobject_controller.go
  pkg/controller/gittrackobject/gittrackobject_controller_suite_test.go
  pkg/controller/gittrackobject/handler.go
  pkg/controller/gittrackobject/handler_test.go
  pkg/controller/gittrackobject/metrics_test.go
  pkg/controller/gittrackobject/status.go
  pkg/controller/gittrackobject/status_test.go
  pkg/controller/gittrackobject/utils/enqueue_owner.go
  pkg/controller/gittrackobject/utils/event_handler.go
  pkg/controller/gittrackobject/watch.go
  pkg/utils/client/apply.go
  pkg/utils/client/client_suite_test.go
Labels: size/L

#137 Add scan and docker-scan make targets
  Makefile
  Makefile.tools
  configure
Labels: size/S

#115 Display invalid files in Status
  config/crds/faros_v1alpha1_gittrack.yaml
  pkg/apis/faros/v1alpha1/gittrack_types.go
  pkg/apis/faros/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/gittrack/fixtures/repo.tgz
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/status.go
  pkg/controller/gittrackobject/gittrackobject_controller_test.go
Labels: size/L

#139 clarify faros YAML
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
Labels: ok-to-test, size/S
