Repository pusher/faros, pull requests merged in 2019-04, with the labels that each got.

#111 Bye bye Wercker!
  wercker.yml
Labels: size/M

#116 Update Controller-Runtime/Tools to v0.1.10
  Gopkg.lock
  Gopkg.toml
  config/rbac/manager_role.yaml
  config/rbac/manager_role_binding.yaml
  pkg/apis/faros/v1alpha1/register.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrackobject/gittrackobject_controller.go
  pkg/controller/gittrackobject/utils/enqueue_owner.go
  pkg/controller/gittrackobject/utils/enqueue_owner_test.go
  pkg/controller/gittrackobject/watch_test.go
  pkg/utils/client/test/delete.go
  pkg/utils/predicate.go
  test/utils/delete.go
  test/utils/matchers.go
Labels: size/L

#117 Use dynamicCodec for decoding errors
  pkg/utils/client/apply.go
Labels: size/XS

#120 Allow disabling dry-run tests
  pkg/utils/client/apply_test.go
  pkg/utils/client/client_suite_test.go
Labels: size/S

#121 Add flag to disable server side dry run
  README.md
  pkg/controller/gittrackobject/handler.go
  pkg/flags/flagset.go
Labels: size/M

#126 Make `make run` run again
  Makefile
Labels: size/XS

#125 Fix linting configuration
  Makefile
  pkg/controller/gittrack/git_creds.go
  pkg/utils/client/patcher.go
Labels: size/S

#128 Update `.gitignore` to reflect current state of affairs
  .gitignore
Labels: size/XS

#127 Add `.dockerignore` to speed up Docker builds
  .dockerignore
Labels: size/XS

#132 Update Dockerfile to match builds produced by `make release`
  Dockerfile
  Makefile
Labels: size/S

#136 Using lazy mapper everywhere
  cmd/manager/main.go
  pkg/utils/rest_mapper.go
Labels: ok-to-test, size/S
