Repository pusher/faros, pull requests merged in 2019-09, with the labels that each got.

#164 Implement GitTrack handler into reconcile
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/handler.go
  pkg/controller/gittrack/handler_test.go
  test/utils/matchers.go
Labels: size/L

#162 Update `git-store` to patched version
  Gopkg.lock
  Gopkg.toml
Labels: size/XS

#167 Update `git-store` to patched version
  Gopkg.lock
  Gopkg.toml
Labels: size/XS

#166 Rewrite tests for fetching Git Credentials
  pkg/controller/gittrack/git_creds.go
  pkg/controller/gittrack/git_creds_test.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
Labels: size/L

#153 Install improvements
  Makefile.tools
Labels: size/XS

#165 cross-namespace access improvements
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_suite_test.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/handler_test.go
  pkg/controller/gittrackobject/gittrackobject_controller.go
  pkg/controller/gittrackobject/handler.go
  pkg/flags/flagset.go
Labels: Project, size/L

#169 Disable clustergittrack
  pkg/controller/gittrack/git_creds_test.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/handler_test.go
Labels: size/L

#173 Make `lint` depend on `vendor`
  Makefile
  pkg/controller/gittrack/metrics.go
  pkg/controller/gittrack/status.go
Labels: size/S

#172 Tests for files-related functions
  pkg/controller/gittrack/files.go
  pkg/controller/gittrack/files_test.go
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/handler_test.go
Labels: size/XL

#170 Disallow having gittracks handle clustergittrackobjects
  pkg/controller/gittrack/fixtures/repo.tgz
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/handler_test.go
Labels: Project, size/M

#177 Reset metrics registry in tests
  pkg/controller/gittrack/gittrack_controller_suite_test.go
  pkg/controller/gittrackobject/gittrackobject_controller_suite_test.go
Labels: size/S

#176 Handle gittracks flag
  pkg/controller/gittrack/gittrack_controller.go
  pkg/controller/gittrack/gittrack_controller_suite_test.go
  pkg/controller/gittrack/gittrack_controller_test.go
  pkg/controller/gittrack/handler.go
  pkg/controller/gittrack/handler_test.go
  pkg/flags/flagset.go
Labels: size/XL
